version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: pass123

  auth:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
